@ECHO OFF
C:
CD "\Users\mpollock\OneDrive\NMU Courses Archive\Fall 2020\CS 120\lab06 club"
"C:\Program Files\Java\jdk-14.0.2\bin\java.exe" -cp .;"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.base.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.controls.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.fxml.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.graphics.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.media.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.swing.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx.web.jar";"C:\Program Files\Java\javafx-sdk-14.0.2.1\lib\javafx-swt.jar" --module-path "C:\Program Files\Java\javafx-sdk-14.0.2.1\lib" --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web Club
PAUSE
